global:
  resolve_timeout: 5m

route:
  receiver: discord

receivers:
  - name: discord
    webhook_configs:
      - url: 'https://discord.com/api/webhooks/1365353324349624483/DaMyVFVQpuWaK5GtFmhaJCDg1mhfwf7VE8Hcm42Yvu7NOCce2joPGPiSh38zbVjay-Sv'
        send_resolved: true

