global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["130.127.89.162:9093"]

rule_files:
  - "/home/chloe/athena_guard/alert_rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["130.127.89.162:9090"]

  - job_name: 'node_exporter'
    static_configs:
      - targets: ["130.127.89.162:9100"]

