global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["${ATHENAGUARD_IP}:${ALERTMANAGER_PORT}"]

rule_files:
  - "${ATHENAGUARD_PATH}/alert_rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["${ATHENAGUARD_IP}:${PROMETHEUS_PORT}"]

  - job_name: 'node_exporter'
    static_configs:
      - targets: ["${ATHENAGUARD_IP}:${NODE_EXPORTER_PORT}"]

